version: '3.8'

services:
  web:
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/notinder
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: notinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build: .
    volumes:
      - .:/notinder
    command: celery -A notinder worker --loglevel=info
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_storage: {}

networks:
  minio-network: