version: '3.8'

services:
  web:
    build: .
    command: bash entrypoint.sh
    volumes:
      - static_volume:/notinder/static
      - media_volume:/notinder/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - media_volume:/notinder/media
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  rabbit:
    hostname: rabbit
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  celery:
    build: .
    command: bash celery-entrypoint.sh
    depends_on:
      - rabbit
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  minio_storage:
  static_volume:
  media_volume:
