# Generated by Django 4.2.4 on 2023-09-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_app', '0002_alter_like_options_alter_match_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_path',
            field=models.TextField(null=True),
        ),
    ]
